### ISSUE TITLE
loss很低但结果异常

### ISSUE THREAD

**Issue by 408550969** [keke-nice/rPPG-MAE#10]
你好，我用自己的训练集进行训练，loss降到0.几，但是预测的时候模型预测的结果完全不对，即使输入训练集也是一样。模型输出的结果是10e^-4，这正常吗？
我只进行了pretrain，但没有运行finetune，这有影响吗？

**Comment by keke-nice** [comment]
你好，pretrain loss 很低是正常的，预测错误意味着需要finetune.


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年8月8日 17:36 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [keke-nice/rPPG-MAE] loss很低但结果异常 (Issue #10) |

你好，我用自己的训练集进行训练，loss降到0.几，但是预测的时候模型预测的结果完全不对，即使输入训练集也是一样。模型输出的结果是10e^-4，这正常吗？
我只进行了pretrain，但没有运行finetune，这有影响吗？

**Comment by 408550969** [comment]
谢谢
