### ISSUE TITLE
Baidu Access Problem

### ISSUE THREAD

**Issue by ErolCitak** [keke-nice/rPPG-MAE#15]
Hey,

Is it possible to share the pre-trained weights on Google Drive or Yandex Drive, .etc? Some people may encounter to register Baidu.

Thanks

**Comment by keke-nice** [comment]
Sure~ You can download the checkpoints from this link https://drive.google.com/drive/folders/19Gl5faxBqd01S9HMPNyk7JsvY8fTaKzD?usp=sharing


---- Replied Message ----
| From | Erol ***@***.***> |
| Date | 12/17/2024 04:50 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [keke-nice/rPPG-MAE] Baidu Access Problem (Issue #15) |

Hey,

Is it possible to share the pre-trained weights on Google Drive or Yandex Drive, .etc? Some people may encounter to register Baidu.

Thanks

**Comment by ErolCitak** [comment]
Great! Thank you @keke-nice
