### ISSUE TITLE
Apply for Weight file 

### ISSUE THREAD

**Issue by wmlgj** [keke-nice/rPPG-MAE#2]
Hello, may I ask if the weight file for pre training can be published and downloaded, and if the training instructions for pre training and fine-tuning can be published? Thank you

**Comment by keke-nice** [comment]
Thanks for your attention. We will update the pre-trained model and more training details in the near future.
---- Replied Message ----
| From | ***@***.***> |
| Date | 3/11/2024 17:33 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [keke-nice/rPPG-MAE] Apply for Weight file (Issue #2) |

Hello, may I ask if the weight file for pre training can be published and downloaded, and if the training instructions for pre training and fine-tuning can be published? Thank you

**Comment by wmlgj** [comment]
Hello, can you provide the download link or training details for PC-STMap.So that I can better reproduce it.
