### ISSUE TITLE
Some imperative problems about STMap in Data Pre-processing stage

### ISSUE THREAD

**Issue by xkwangcn** [keke-nice/rPPG-MAE#4]
## Question
How to get CHROM-STMap, POS-STMap, Filtered-STMap, and original-STMap?

### What did you do?
I have successfully run the  [code](https://github.com/keke-nice/rPPG-MAE/blob/main/Data/STMap_CSI.py), but still confused about how to implement the code for different STMaps.

Could you provide us the specific run steps and key parameters for different STMaps. Thank you very much.

**Comment by xkwangcn** [comment]
@keke-nice hello, could you provide me the complete code when you are convenient, thank you very much.

**Comment by keke-nice** [comment]
Please refer to the data pre-processing section for instructions on how to get the different types of STMaps. You should get the original STMap first, and then implement the corresponding processing on this basis to get other types of STMaps.

**Comment by xkwangcn** [comment]
> Please refer to the data pre-processing section for instructions on how to get the different types of STMaps. You should get the original STMap first, and then implement the corresponding processing on this basis to get other types of STMaps.

Thanks for your reply, I have tried the code in STMap_CSI.py, but there are many values equal to 0 after this line (`BGRNorm[:, j] = STMap_CSI[WinS:WinE, j]/(BGRBase+0.0001) - 1`), could you provide me the complete code if convenient. Thank you very much.

**Comment by keke-nice** [comment]
> > Please refer to the data pre-processing section for instructions on how to get the different types of STMaps. You should get the original STMap first, and then implement the corresponding processing on this basis to get other types of STMaps.
> 
> Thanks for your reply, I have tried the code in STMap_CSI.py, but there are many values equal to 0 after this line (`BGRNorm[:, j] = STMap_CSI[WinS:WinE, j]/(BGRBase+0.0001) - 1`), could you provide me the complete code if convenient. Thank you very much.

Please refer to the complete code here.  [[VIPL](https://github.com/EnVision-Research/NEST-rPPG/tree/main/STMap/VIPL)](https://github.com/EnVision-Research/NEST-rPPG/tree/main/STMap/VIPL)

**Comment by xkwangcn** [comment]
> > > Please refer to the data pre-processing section for instructions on how to get the different types of STMaps. You should get the original STMap first, and then implement the corresponding processing on this basis to get other types of STMaps.
> > 
> > 
> > Thanks for your reply, I have tried the code in STMap_CSI.py, but there are many values equal to 0 after this line (`BGRNorm[:, j] = STMap_CSI[WinS:WinE, j]/(BGRBase+0.0001) - 1`), could you provide me the complete code if convenient. Thank you very much.
> 
> Please refer to the complete code here. [[VIPL](https://github.com/EnVision-Research/NEST-rPPG/tree/main/STMap/VIPL)](https://github.com/EnVision-Research/NEST-rPPG/tree/main/STMap/VIPL)

But the CHROM and POS values are from BUAA code https://github.com/EnVision-Research/NEST-rPPG/tree/main/STMap/BUAA not VIPL, correct?

**Comment by keke-nice** [comment]
> > > > Please refer to the data pre-processing section for instructions on how to get the different types of STMaps. You should get the original STMap first, and then implement the corresponding processing on this basis to get other types of STMaps.
> > > 
> > > 
> > > Thanks for your reply, I have tried the code in STMap_CSI.py, but there are many values equal to 0 after this line (`BGRNorm[:, j] = STMap_CSI[WinS:WinE, j]/(BGRBase+0.0001) - 1`), could you provide me the complete code if convenient. Thank you very much.
> > 
> > 
> > Please refer to the complete code here. [[VIPL](https://github.com/EnVision-Research/NEST-rPPG/tree/main/STMap/VIPL)](https://github.com/EnVision-Research/NEST-rPPG/tree/main/STMap/VIPL)
> 
> But the CHROM and POS values are from BUAA code https://github.com/EnVision-Research/NEST-rPPG/tree/main/STMap/BUAA not VIPL, correct?

The CHROM and POS algorithm can be used in any STMap and any dataset.

**Comment by gaiya10** [comment]
@keke-nice  We are currently in the process of applying for the PURE and UBFC-rPPG datasets, and due to the urgency of our research, May I kindly inquire if it would be possible to upload the STMap of these datasets to Baidu pan?

**Comment by keke-nice** [comment]
> @keke-nice We are currently in the process of applying for the PURE and UBFC-rPPG datasets, and due to the urgency of our research, May I kindly inquire if it would be possible to upload the STMap of these datasets to Baidu pan?

Sure! Link：https://pan.baidu.com/s/19nboNiXbpoSt8b8_3s840A  Code：2xys Don't forget to cite our work~

**Comment by gaiya10** [comment]
@keke-nice Thank you for your generous sharing, and I will definitely cite your work. I wish your research goes smoothly!

**Comment by 111qing** [comment]
> @keke-nice Thank you for your generous sharing, and I will definitely cite your work. I wish your research goes smoothly!

Hello, the Baidu Netdisk link shared by the author earlier has expired. Could you please share it with me again?thank  you very much

**Comment by urbaneman** [comment]
> > @keke-nice We are currently in the process of applying for the PURE and UBFC-rPPG datasets, and due to the urgency of our research, May I kindly inquire if it would be possible to upload the STMap of these datasets to Baidu pan?
> 
> Sure! Link：https://pan.baidu.com/s/19nboNiXbpoSt8b8_3s840A Code：2xys Don't forget to cite our work~

@keke-nice @gaiya10 
Thank you for your great work. I noticed that the link to the shared data has expired. I am currently applying for the PURE dataset, but time is tight. Could you please re-share the relevant dataset? I will comply with the associated protocols. Thank you!

**Comment by keke-nice** [comment]
Link: https://pan.baidu.com/s/1TZPI1GxDgXJfXrzgneP4RA?pwd=d4ti Code: d4ti

Hope it might be helpful~ :)
---- Replied Message ----
| From | ***@***.***> |
| Date | 11/25/2024 15:29 |
| To | ***@***.***> |
| Cc | Yuting ***@***.***> ,
***@***.***> |
| Subject | Re: [keke-nice/rPPG-MAE] Some imperative problems about STMap in Data Pre-processing stage (Issue #4) |

@keke-nice We are currently in the process of applying for the PURE and UBFC-rPPG datasets, and due to the urgency of our research, May I kindly inquire if it would be possible to upload the STMap of these datasets to Baidu pan?

Sure! Link：https://pan.baidu.com/s/19nboNiXbpoSt8b8_3s840A Code：2xys Don't forget to cite our work~

@***@***.***
Thank you for your great work. I noticed that the link to the shared data has expired. I am currently applying for the PURE dataset, but time is tight. Could you please re-share the relevant dataset? I will comply with the associated protocols. Thank you!

**Comment by urbaneman** [comment]
@keke-nice Thank you for your response. I have downloaded the data and found that it is the STMap dataset. Could you share the **original dataset** with the videos? I would like to visualize them and perform some visualizations directly on the original videos to better analyze the data.

> Link: https://pan.baidu.com/s/1TZPI1GxDgXJfXrzgneP4RA?pwd=d4ti Code: d4ti

**Comment by keke-nice** [comment]
Link: https://pan.baidu.com/s/1JkPPq9eDE4ieBR51m7s1xA?pwd=dd2s Code:dd2s



---- Replied Message ----
| From | ***@***.***> |
| Date | 11/25/2024 16:12 |
| To | ***@***.***> |
| Cc | Yuting ***@***.***> ,
***@***.***> |
| Subject | Re: [keke-nice/rPPG-MAE] Some imperative problems about STMap in Data Pre-processing stage (Issue #4) |

@keke-nice Thank you for your response. I have downloaded the data and found that it is the STMap dataset. Could you share the original dataset with the videos? I would like to visualize them and perform some visualizations directly on the original videos to better analyze the data.

Link: https://pan.baidu.com/s/1TZPI1GxDgXJfXrzgneP4RA?pwd=d4ti Code: d4ti

**Comment by urbaneman** [comment]
@keke-nice Thank you once again!  I will comply with the associated licenses. Wishing you success in your future researchs.

**Comment by urbaneman** [comment]
@keke-nice Hi, I follow this code to generate POS & CHROM signal.

> Please refer to the complete code here. [[VIPL](https://github.com/EnVision-Research/NEST-rPPG/tree/main/STMap/VIPL)](https://github.com/EnVision-Research/NEST-rPPG/tree/main/STMap/VIPL)

However, I find the [POS func](https://github.com/EnVision-Research/NEST-rPPG/blob/642af482f138757bec0cfcd89ac520585e49306f/STMap/BUAA/STMap.py#L142~L162) may have bug, it **not cutoff signal out of LPF-HPF**:


```python
def POS(STMap_CSI):
    LPF = 0.7  # low cutoff frequency(Hz) - specified as 40bpm(~0.667Hz) in reference
    HPF = 2.5  # high cutoff frequency(Hz) - specified as 240bpm(~4.0Hz) in reference
    WinSec = 1.6  # (was a 48 frame window with 30 fps camera)
    NyquistF = 15  # 30fps
    FS = 30  # 30fps
    N = STMap_CSI.shape[0]
    l = int(WinSec * FS)
    H = np.zeros(N)
    Cn = np.zeros((3, l))
    P = np.array([[0, 1, -1], [-2, 1, 1]])
    for n in range(N-1):
        m = n - l
        if m >= 0:
            Cn[0, :] = STMap_CSI[m:n, 2]/np.nanmean(STMap_CSI[m:n, 2])
            Cn[1, :] = STMap_CSI[m:n, 1]/np.nanmean(STMap_CSI[m:n, 1])
            Cn[2, :] = STMap_CSI[m:n, 0]/np.nanmean(STMap_CSI[m:n, 0])
            S = np.dot(P, Cn)
            h = S[0, :] + ((np.nanstd(S[0, :])/np.nanstd(S[1, :]))*S[1, :])
            H[m: n] = H[m: n] + (h - np.nanmean(h))
    return H
```

And the generate func in [rPPG-Toolbox](https://github.com/ubicomplab/rPPG-Toolbox/blob/7c0604b5a5f7d0a6e6919515a081caa56dd7ce8b/unsupervised_methods/methods/POS_WANG.py#L45) cutoff the noise

```python
def POS_WANG(frames, fs):
    WinSec = 1.6
    RGB = _process_video(frames)
    N = RGB.shape[0]
    H = np.zeros((1, N))
    l = math.ceil(WinSec * fs)

    for n in range(N):
        m = n - l
        if m >= 0:
            Cn = np.true_divide(RGB[m:n, :], np.mean(RGB[m:n, :], axis=0))
            Cn = np.mat(Cn).H
            S = np.matmul(np.array([[0, 1, -1], [-2, 1, 1]]), Cn)
            h = S[0, :] + (np.std(S[0, :]) / np.std(S[1, :])) * S[1, :]
            mean_h = np.mean(h)
            for temp in range(h.shape[1]):
                h[0, temp] = h[0, temp] - mean_h
            H[0, m:n] = H[0, m:n] + (h[0])

    BVP = H
    BVP = utils.detrend(np.mat(BVP).H, 100)
    BVP = np.asarray(np.transpose(BVP))[0]
    b, a = signal.butter(1, [0.75 / fs * 2, 3 / fs * 2], btype='bandpass')
    BVP = signal.filtfilt(b, a, BVP.astype(np.double))
    return BVP
```

Have you noticed this issue? Or does this part have no impact on the final result?

**Comment by Zackary-Lykos** [comment]
> > @keke-nice We are currently in the process of applying for the PURE and UBFC-rPPG datasets, and due to the urgency of our research, May I kindly inquire if it would be possible to upload the STMap of these datasets to Baidu pan?
> 
> Sure! Link：https://pan.baidu.com/s/19nboNiXbpoSt8b8_3s840A Code：2xys Don't forget to cite our work~

Hi, the shared link has expired, could you share the CHROM & POS - STMap of UBFC-rPPG again? Thank you very much!

**Comment by jiangmengxuan** [comment]
> > [@keke-nice](https://github.com/keke-nice) We are currently in the process of applying for the PURE and UBFC-rPPG datasets, and due to the urgency of our research, May I kindly inquire if it would be possible to upload the STMap of these datasets to Baidu pan?
> 
> Sure! Link：https://pan.baidu.com/s/19nboNiXbpoSt8b8_3s840A Code：2xys Don't forget to cite our work~

Thank you for your great work. I noticed that the link to the shared data has expired. I am currently applying for the PURE and UBFC-rPPG datasets, but time is tight. Could you please kindly re-share the STMaps of these two datasets? I will comply with the associated protocols. Thank you!
