### ISSUE TITLE
RuntimeError: Given normalized_shape=[768], expected input with shape [*, 768], but got input of size[64]

### ISSUE THREAD

**Issue by peizhengfu** [keke-nice/rPPG-MAE#6]
你好，在我进行模型微调时代码运行时报错如下：
![屏幕截图 2024-05-17 173414](https://github.com/keke-nice/rPPG-MAE/assets/50606839/e14db092-ddf9-43fa-b6c1-8ba7f1cb5110)
请问这是什么原因导致的

**Comment by keke-nice** [comment]
您好，我提供的代码应该是正常的，您可以check一下输入是否有问题。
