### ISSUE TITLE
数据必须满足224的倍数吗？

### ISSUE THREAD

**Issue by 408550969** [keke-nice/rPPG-MAE#9]
你好，我刚看到rPPG-MAE，对代码不是很熟悉，请问如果我要训练自己的数据集，我的数据集必须满足224的倍数吗，如果没有满足依旧可以训练吗？其次，该算法能否可以在驾驶场景下进行心率检测即当头部在不停抖动时，该算法是否可以进行预测，目前自测下来TS-CAN、EfficientPhys等方法都只能检测静态场景，一旦动起来就预测不准了。

**Comment by Zackary-Lykos** [comment]
> 你好，我刚看到rPPG-MAE，对代码不是很熟悉，请问如果我要训练自己的数据集，我的数据集必须满足224的倍数吗，如果没有满足依旧可以训练吗？其次，该算法能否可以在驾驶场景下进行心率检测即当头部在不停抖动时，该算法是否可以进行预测，目前自测下来TS-CAN、EfficientPhys等方法都只能检测静态场景，一旦动起来就预测不准了。

大佬后来有发现可以在驾驶场景下准确预测的算法吗？目前已经尝试physformer和rppgmae，两者都存在漏波（①每个波都有一点偏移，时间长了就漏个波；②某一瞬间预测波形只有个大凸起，覆盖了GT的2~2.5个波）的问题；预测心率尚可接受，但是计算更高精度要求的参数时就芜湖了🤦‍。
